name: moor_flutter
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependency_overrides:
  path: 1.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  moor: ^3.4.0
  sqlite3_flutter_libs: 0.3.0
  path_provider: ^1.6.24
  path: 1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.9.0
  moor_generator: 3.4.0
  build_runner: 1.10.11
  mobx_codegen: 1.1.2

flutter:

  uses-material-design: true


