name: moor_flutter
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

#dependency_overrides:
#  path: 1.8.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  mobx: 2.1.3
  flutter_mobx: 2.0.6+5
  drift: 2.4.2
  sqlite3_flutter_libs: 0.5.12
  path_provider: 2.0.11
  path: 1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
#  moor_generator: 4.6.0+1
  build_runner: 2.3.3
  mobx_codegen: 2.1.1
  drift_dev: ^2.4.1
  network_image_mock: 2.1.1

flutter:
  uses-material-design: true


